### ISSUE TITLE
Problem with Configurable Products

### ISSUE THREAD

**Issue by chequille** [Magenerds/BasePrice#1]
Hi,
I am trying the BasePrice Modul and was succesfull to get it working with simple products.

Unfortunately, it is not working for me with configurable products.

In the product view page, it is showing the baseprice of the main product, but when changing an option it still shows the same baseprice output.
I found, that the script in configurable/afterprice.phtml is giving an error: swatchWidget is undefined

I am using Magento2 Version 2.1.0 and the Luma Theme

Do you have any idea?
Best regards,
Jürgen

**Comment by chequille** [comment]
Hi,
just to let you know that it is working when the option is configured as Visual or Textual Swatch. Makes sense, because than the base swatch Scripts are included.

Question: do you plan to support this as well for normal dropdown options?

Looking forward to hearing from you.

Best regards,
Jürgen

**Comment by sydekumf** [comment]
Hi there,
sorry for the delay, here is the fix: https://github.com/Magenerds/BasePrice/releases/tag/1.0.8
