### ISSUE TITLE
Unit 'labels' (options) are gone

### ISSUE THREAD

**Issue by fwolfst** [Magenerds/BasePrice#12]
In a magento 2.1.9 shop we do not see any "units" anymore, the respective select fields are empty (there is a "select value" thing though). I am not 100% sure but I think it did work before. This might be connected to a recent update (from 2.1.x).

The conversion rules are still shown, but with empty selected units.

Is there a simple way to repopulate the options ("kg", "g", ...), or a quick pointer about how to find the relevant fields via SQL and fix them accordingly?

**Comment by fwolfst** [comment]
Afaiu the options for the respective attribute(s) do not exist.

**Comment by fwolfst** [comment]
So I had to recreate by hand :( . Uninstallation and reinstallation did not solve the issue.

**Comment by sydekumf** [comment]
Thanks! This is fixed in this commit, release is following: https://github.com/Magenerds/BasePrice/commit/01c3a11b05ec8f23d15f07be71d818e49ba852b3
