### ISSUE TITLE
Base price result wrong when prices in backend catalog are excl. tax but display inc. tax

### ISSUE THREAD

**Issue by violuke** [Magenerds/BasePrice#13]
The same as #6.

Prices entered into the admin without tax, but displayed on the website with tax have the wrong base price shown. I'll try to resolve it, but if anyone else can help that would be much appreciated.

![bug](https://user-images.githubusercontent.com/6420347/32001314-b3155690-b999-11e7-9da8-1a4b39548b11.jpeg)

**Comment by violuke** [comment]
I don't know if this will work properly for other scenarios regarding tax display/admin input but I resolved this for us by changing line [128 of Magenerds/BasePrice/Helper/Data.php](https://github.com/Magenerds/BasePrice/blob/3fbe761a59b37cef90593d60186a9165b13a1255/Helper/Data.php#L128) from 
```php
$productPrice = $product->getFinalPrice();
```
to
```php
$productPrice = (string)round((string)$product->getPriceInfo()->getPrice('final_price')->getAmount(), 4);
```

**Comment by sydekumf** [comment]
Thanks for the report, we fixed it :-)
