### ISSUE TITLE
error on magento 2.2.1

### ISSUE THREAD

**Issue by matin73** [Magenerds/BasePrice#18]
I installed module in latest magento and if I want to go to shops -> configuration -> magenerds -> base price an error occures:
1 exception(s):
Exception #0 (InvalidArgumentException): Unable to unserialize value.

**Comment by chequille** [comment]
Hi,
I get a similar error as well with a fresh installed Magento 2.2.1, but not in the frontend.
When BasePrice is enabled, frontend throws the following error:

1 exception(s):
Exception #0 (Exception): Notice: unserialize(): Error at offset 0 of 173 bytes in /var/www/vhosts/chequille.de/httpdocs/magento/app/code/Magenerds/BasePrice/Helper/Data.php on line 63

This line try to get the SCOPEs of the store.

Don't know if this is really a bug from BasePRice or maybe some other wrong configuration at some place.

Do you have any idea what this could be?
Best regards
Jürgen
