### ISSUE TITLE
all units are gone?

### ISSUE THREAD

**Issue by perler** [Magenerds/BasePrice#29]
I installed the extension on  2.2.1 and suddenly the units are gone: https://www.screencast.com/t/XwEwc3HrFN9H

this is a development server so a lot of things might have happened - is there a simple way to restore the default units?

**Comment by sydekumf** [comment]
We know that the serialization logic changed from M 2.1 to M 2.2. It often helped to delete all entries in the `core_config_data` table and resave the configuration.

**Comment by perler** [comment]
I tried this but it didn't work. I had these values in core_config_data, removed them, reloaded the configuration page, saved it and had the same values again and no units:

```
config_id	scope	scope_id	path	value
612	default	0	baseprice/general/enabled	1
613	default	0	baseprice/general/template	{BASE_PRICE} / {REF_AMOUNT} {REF_UNIT}
614	default	0	baseprice/general/conversion	[{"product_unit":"","reference_unit":"","conversion_rate":"0.001"},{"product_unit":"","reference_unit":"","conversion_rate":"0.000001"},{"product_unit":"","reference_unit":"","conversion_rate":"1000"},{"product_unit":"","reference_unit":"","conversion_rate":"0.000001"},{"product_unit":"","reference_unit":"","conversion_rate":"1000000"},{"product_unit":"","reference_unit":"","conversion_rate":"1000"},{"product_unit":"","reference_unit":"","conversion_rate":"0.001"},{"product_unit":"","reference_unit":"","conversion_rate":"1000"},{"product_unit":"","reference_unit":"","conversion_rate":"0.001"},{"product_unit":"","reference_unit":"","conversion_rate":"0.000001"},{"product_unit":"","reference_unit":"","conversion_rate":"1000"},{"product_unit":"","reference_unit":"","conversion_rate":"0.001"},{"product_unit":"","reference_unit":"","conversion_rate":"1000000"},{"product_unit":"","reference_unit":"","conversion_rate":"1000"}]
```

**Comment by perler** [comment]
we still have this issue, is there really no way to completely reset the extension?

**Comment by sydekumf** [comment]
You can uninstall the extension and install it again. The units get installed in the two product attribtues `baseprice_product_unit` and `baseprice_reference_unit`. So I assume someone deleted them from there? Look in Store->Attribtues-Product

**Comment by perler** [comment]
ok, as the installation according to here http://doc.magenerds.com/extension-installation/ is only working via file transfer, what is the proper way to remove it? or is there a composer installation (and removal) possible?

**Comment by perler** [comment]
..an yes, someone seems to have removed the attributes. we have a purpose built migration script from magento 1 to 2 and it may have wrecked some havoc (that's why we want to reset the extension)

**Comment by sydekumf** [comment]
If you installed it via composer you can also deinstall it via composer. But I am pretty sure if you insert the units again in the product attribtues, you will see them again. I will close this ticket, as I think this resolves your problem. If not, just reopen it :-)

**Comment by perler** [comment]
ok, it's 

`composer require Magenerds/BasePrice`

but even after 

`composer remove Magenerds/BasePrice`

(and setup/cache:flush) the unit's don't reappear. 

yes, I could add them by hand, but I really would like to have the default values in the extension to avoid any problems going forward.. an SQL statement to add the values straight into the DB would be fine..

**Comment by sydekumf** [comment]
They are only installed on initial installation of the module.

**Comment by perler** [comment]
ok, can someone post a screenshot of the original installation (like this one: https://www.screencast.com/t/h7gHFwQcYz)
