### ISSUE TITLE
Not compatible with 2.3

### ISSUE THREAD

**Issue by in-session** [Magenerds/BasePrice#40]
Modul is not working on Magento 2.3, product attributes are not created in the database.

**Comment by MarcusWolschon** [comment]
Release 2.0.0 claims to be compatible with Magento 2.3
https://github.com/Magenerds/BasePrice/releases/tag/2.0.0

Since it's 1.3->2.0 , is there anything special to be careful about when upgrading?

**Comment by celocore** [comment]
Hello,

we installed the module using composer under Magento 2.3.1. There were no error messages. But in the backend the conversion mappings under Stores -> Configuration -> Magenerds -> Base Price are missing.

Any ideas?

**Comment by MarcusWolschon** [comment]
I tried with 2.3.1 and   Stores -> Configuration -> Magenerds -> Base Price exists and looks fine. (English version)

**Comment by celocore** [comment]
Have you installed it via composer oder as described at the Magenerds homepage?

**Comment by MarcusWolschon** [comment]
Updated existing setup via composer.

**Comment by celocore** [comment]
We haven't edited any file manually. We've installed it fresh via composer.

**Comment by Songworks** [comment]
I've installed this extension through composer on a (for the most part basic) Magento ver 2.3.1 and it seems to work fine so far.

Steps:

```
composer require Magenerds/BasePrice ^2.0.0
php bin/magento setup:upgrade
php bin/magento setup:di:compile
php bin/magento cache:flush
```

Also ran indexer:reindex but probably not necessary.

Cheers!

**Comment by YiffyToys** [comment]
No problems after upgrading to 2.3.2 either.

**Comment by unixversal** [comment]
also can confirm working in Magento 2.3.4 version.
