### ISSUE TITLE
BasePrice in New_List Widget

### ISSUE THREAD

**Issue by chequille** [Magenerds/BasePrice#5]
Hi,

I know, thias modul is free and therefore support is not garanteed, but nevertheless, I want to report some issues which I found and could not solve myself so far.

It is regarding a block with new products, using the new_list.phtml widget as of the Luma theme.

If you have a configurable product with swatches, the output of the products in the new_list block is also changing. Of course this is not correct.

Do you have any idea how to solve this? Maybe disableing the plugin in a certain block.

You can have a look to see what I mean. It is on the following link: magento.hopfenexpress.de/pale-ale

On the right hand site of the screen you can see 2 new products. If you select in the middle of the screen the swatches 0.33l or 0.75l the display of "Grundpreis ....." for the new products is also changing.

Would be nice if you think about it.

Thanks and best regards,

Jürgen

**Comment by sydekumf** [comment]
Hi there,
thanks for the reporting. The problem already got fixed and is available in this version: https://github.com/Magenerds/BasePrice/releases/tag/1.0.4

In detail this fixes the problem: https://github.com/Magenerds/BasePrice/commit/ee11d85014551bbafdd50abd1e46a5059ad9ae0b
