### ISSUE TITLE
Base price result wrong when prices in backend catalog are excl. tax

### ISSUE THREAD

**Issue by JSchmidt63** [Magenerds/BasePrice#6]
Hi,
when prices in backend catalog are setup as excluding tax. The baseprice module picks up that price and calculates the baseprice on that. Sadly though the result shown is incorrect if there are taxes applied to the price in the frontend. Obviously the applied Tax is not taken into account.

Example in the picture: backend catalog price is 13.44€ ex. tax included in the frontend price is 19%. The product amount for base price calculation is 30ml and the reference amount is 1ml.

Magento Version 2.1.3, Module Version 1.0.4

![price-ex-tax](https://cloud.githubusercontent.com/assets/25293774/22195484/89fe2946-e148-11e6-98e7-255799dd0f9a.PNG)

**Comment by sydekumf** [comment]
Hi there,
thanks for reporting. Unfortunately I cannot reproduce this. I am not sure if I understood you correctly. I have set the following system configuration: Sales -> Tax -> Calculation Settings -> Catalog Prices: Excluding Tax.

I have a product in the backend with 29€ and in frontend 19% tax get added to it, so it has a price of 34,51€. 30ml -> 1ml this will be 1,15€ then.

This is what I got:
![bildschirmfoto 2017-03-18 um 20 15 34](https://cloud.githubusercontent.com/assets/3983052/24075246/da561e04-0c17-11e7-9892-24b92bd09478.png)

**Comment by JSchmidt63** [comment]
Hi there,
that's exactly what i meant. Odd. Close the ticket then. Cheers.

**Comment by sydekumf** [comment]
So you can not reproduce it either?

**Comment by JSchmidt63** [comment]
I still can reproduce it, but i blame another bugsource meanwhile. I see the problem in other parts of the application as well.

**Comment by sydekumf** [comment]
Okay, if you still have problems somewhere, feel free to open an issue again :-)

**Comment by violuke** [comment]
I have this same issue. Prices entered into the admin without tax, but displayed on the website with tax. I'll try to resolve it, but if anyone else can help that would be much appreciated.

![bug](https://user-images.githubusercontent.com/6420347/32001314-b3155690-b999-11e7-9da8-1a4b39548b11.jpeg)
