### ISSUE TITLE
Can't install magento with this module present

### ISSUE THREAD

**Issue by m-schreiber** [Magenerds/BasePrice#8]
To recreate:
* composer create-project (best with requirement for baseprice 1.0.8)
* run setup:install
* bang

.... bin/magento setup:install ...

Starting Magento installation:
File permissions check...
[Progress: 1 / 438]
Required extensions check...
[Progress: 2 / 438]
Enabling Maintenance Mode...
[Progress: 3 / 438]
Installing deployment configuration...
[Progress: 4 / 438]
Cleaning up database...
Cleaning up database `magento2`
[Progress: 5 / 438]
Installing database schema:
Schema creation/updates:
Module 'Magento_Store':
Installing schema...
[Progress: 6 / 438]
Module 'Magenerds_Dashboard':
[Progress: 7 / 438]
Module 'Magento_Directory':
Installing schema...
[Progress: 8 / 438]
Module 'Magento_Theme':
Installing schema...
[Progress: 9 / 438]
Module 'Magento_AdvancedPricingImportExport':
[Progress: 10 / 438]
Module 'Magento_Backend':
[Progress: 11 / 438]
Module 'Magento_Eav':
Installing schema...
[Progress: 12 / 438]
Module 'Magento_Customer':
Installing schema... Upgrading schema...
[Progress: 13 / 438]
Module 'Magento_Backup':
[Progress: 14 / 438]
Module 'Magento_AdminNotification':
Installing schema...
[Progress: 15 / 438]
Module 'Magento_Indexer':
Installing schema...
[Progress: 16 / 438]
Module 'Magento_BundleImportExport':
[Progress: 17 / 438]
Module 'Magento_CacheInvalidate':
[Progress: 18 / 438]
Module 'Magento_Cms':
Installing schema... Upgrading schema...
[Progress: 19 / 438]
Module 'Magento_Config':
Installing schema...
[Progress: 20 / 438]
Module 'Magento_CatalogImportExport':
[Progress: 21 / 438]
Module 'Magento_Catalog':
Installing schema... Upgrading schema...
[Progress: 22 / 438]
Module 'Magento_Rule':
[Progress: 23 / 438]
Module 'Magento_Msrp':
[Progress: 24 / 438]
Module 'Magento_Search':
Installing schema... Upgrading schema...
[Progress: 25 / 438]
Module 'Magento_CatalogUrlRewrite':
Installing schema...
[Progress: 26 / 438]
Module 'Magento_Widget':
Installing schema...
[Progress: 27 / 438]
Module 'Magento_Quote':
Installing schema... Upgrading schema...
[Progress: 28 / 438]
Module 'Magento_CheckoutAgreements':
Installing schema... Upgrading schema...
[Progress: 29 / 438]
Module 'Magento_SalesSequence':
Installing schema...
[Progress: 30 / 438]
Module 'Magento_CmsUrlRewrite':
[Progress: 31 / 438]
Module 'Magenerds_BasePrice':
[Progress: 32 / 438]
Module 'Magento_ConfigurableImportExport':
[Progress: 33 / 438]
Module 'Magento_Payment':
[Progress: 34 / 438]
Module 'Magento_Contact':
[Progress: 35 / 438]
Module 'Magento_Cookie':
[Progress: 36 / 438]
Module 'Magento_Cron':
Installing schema...
[Progress: 37 / 438]
Module 'Magento_CurrencySymbol':
[Progress: 38 / 438]
Module 'Magento_User':
Installing schema... Upgrading schema...
[Progress: 39 / 438]
Module 'Magento_CustomerImportExport':
[Progress: 40 / 438]
Module 'Magento_Deploy':
[Progress: 41 / 438]
Module 'Magento_Developer':
[Progress: 42 / 438]
Module 'Magento_Dhl':
[Progress: 43 / 438]
Module 'Magento_Authorization':
Installing schema...
[Progress: 44 / 438]
Module 'Magento_Downloadable':
Installing schema...
[Progress: 45 / 438]
Module 'Magento_ImportExport':
Installing schema... Upgrading schema...
[Progress: 46 / 438]
Module 'Magento_CatalogInventory':
Installing schema...
[Progress: 47 / 438]
Module 'Magento_Email':
Installing schema...
[Progress: 48 / 438]
Module 'Magento_EncryptionKey':
[Progress: 49 / 438]
Module 'Magento_Fedex':
[Progress: 50 / 438]
Module 'Magento_Sales':
Installing schema... Upgrading schema...
[Progress: 51 / 438]
Module 'Magento_Checkout':
[Progress: 52 / 438]
Module 'Magento_GoogleAnalytics':
[Progress: 53 / 438]
Module 'Magento_Ui':
Installing schema...
[Progress: 54 / 438]
Module 'Magento_GroupedImportExport':
[Progress: 55 / 438]
Module 'Magento_GroupedProduct':
[Progress: 56 / 438]
Module 'Magento_DownloadableImportExport':
[Progress: 57 / 438]
Module 'Magento_Bundle':
Installing schema... Upgrading schema...
[Progress: 58 / 438]
Module 'Magento_Security':
Installing schema... Upgrading schema...
[Progress: 59 / 438]
Module 'Magento_LayeredNavigation':
[Progress: 60 / 438]
Module 'Magento_Marketplace':
[Progress: 61 / 438]
Module 'Magento_MediaStorage':
[Progress: 62 / 438]
Module 'Magento_CatalogRule':
Installing schema... Upgrading schema...
[Progress: 63 / 438]
Module 'Magento_Multishipping':
[Progress: 64 / 438]
Module 'Magento_ConfigurableProduct':
Installing schema...
[Progress: 65 / 438]
Module 'Magento_Newsletter':
Installing schema...
[Progress: 66 / 438]
Module 'Magento_OfflinePayments':
[Progress: 67 / 438]
Module 'Magento_SalesRule':
Installing schema... Upgrading schema...
[Progress: 68 / 438]
Module 'Magento_PageCache':
[Progress: 69 / 438]
Module 'Magento_Vault':
Installing schema...
[Progress: 70 / 438]
Module 'Magento_Paypal':
Installing schema...
[Progress: 71 / 438]
Module 'Magento_Persistent':
Installing schema...
[Progress: 72 / 438]
Module 'Magento_ProductAlert':
Installing schema...
[Progress: 73 / 438]
Module 'Magento_ProductVideo':
Installing schema...
[Progress: 74 / 438]
Module 'Magento_Captcha':
Installing schema...
[Progress: 75 / 438]
Module 'Magento_Reports':
Installing schema...
[Progress: 76 / 438]
Module 'Magento_RequireJs':
[Progress: 77 / 438]
Module 'Magento_Review':
Installing schema...
[Progress: 78 / 438]
Module 'Magento_Rss':
[Progress: 79 / 438]
Module 'Magento_CatalogRuleConfigurable':
[Progress: 80 / 438]
Module 'Magento_NewRelicReporting':
Installing schema...
[Progress: 81 / 438]
Module 'Magento_SalesInventory':
[Progress: 82 / 438]
Module 'Magento_OfflineShipping':
Installing schema...
[Progress: 83 / 438]
Module 'Magento_Authorizenet':
[Progress: 84 / 438]
Module 'Magento_SampleData':
[Progress: 85 / 438]
Module 'Magento_CatalogSearch':
Installing schema...
[Progress: 86 / 438]
Module 'Magento_Integration':
Installing schema... Upgrading schema...
[Progress: 87 / 438]
Module 'Magento_SendFriend':
Installing schema...
[Progress: 88 / 438]
Module 'Magento_Shipping':
[Progress: 89 / 438]
Module 'Magento_Sitemap':
Installing schema...
[Progress: 90 / 438]
Module 'Magento_GoogleAdwords':
[Progress: 91 / 438]
Module 'Magento_Swagger':
[Progress: 92 / 438]
Module 'Magento_Swatches':
Installing schema...
[Progress: 93 / 438]
Module 'Magento_SwatchesLayeredNavigation':
[Progress: 94 / 438]
Module 'Magento_Tax':
Installing schema...
[Progress: 95 / 438]
Module 'Magento_TaxImportExport':
[Progress: 96 / 438]
Module 'Magento_GiftMessage':
Installing schema...
[Progress: 97 / 438]
Module 'Magento_Translation':
Installing schema...
[Progress: 98 / 438]
Module 'Magento_GoogleOptimizer':
Installing schema...
[Progress: 99 / 438]
Module 'Magento_Ups':
[Progress: 100 / 438]
Module 'Magento_UrlRewrite':
Installing schema...
[Progress: 101 / 438]
Module 'Magenerds_GermanLaw':
[Progress: 102 / 438]
Module 'Magento_Usps':
[Progress: 103 / 438]
Module 'Magento_Variable':
Installing schema...
[Progress: 104 / 438]
Module 'Magento_Braintree':
[Progress: 105 / 438]
Module 'Magento_Version':
[Progress: 106 / 438]
Module 'Magento_Webapi':
[Progress: 107 / 438]
Module 'Magento_WebapiSecurity':
[Progress: 108 / 438]
Module 'Magento_Weee':
Installing schema...
[Progress: 109 / 438]
Module 'Magento_CatalogWidget':
[Progress: 110 / 438]
Module 'Magento_Wishlist':
Installing schema...
[Progress: 111 / 438]
Schema post-updates:
Module 'Magento_Store':
[Progress: 112 / 438]
Module 'Magenerds_Dashboard':
[Progress: 113 / 438]
Module 'Magento_Directory':
[Progress: 114 / 438]
Module 'Magento_Theme':
[Progress: 115 / 438]
Module 'Magento_AdvancedPricingImportExport':
[Progress: 116 / 438]
Module 'Magento_Backend':
[Progress: 117 / 438]
Module 'Magento_Eav':
[Progress: 118 / 438]
Module 'Magento_Customer':
[Progress: 119 / 438]
Module 'Magento_Backup':
[Progress: 120 / 438]
Module 'Magento_AdminNotification':
[Progress: 121 / 438]
Module 'Magento_Indexer':
Running schema recurring...
[Progress: 122 / 438]
Module 'Magento_BundleImportExport':
[Progress: 123 / 438]
Module 'Magento_CacheInvalidate':
[Progress: 124 / 438]
Module 'Magento_Cms':
[Progress: 125 / 438]
Module 'Magento_Config':
[Progress: 126 / 438]
Module 'Magento_CatalogImportExport':
[Progress: 127 / 438]
Module 'Magento_Catalog':
Running schema recurring...
[Progress: 128 / 438]
Module 'Magento_Rule':
[Progress: 129 / 438]
Module 'Magento_Msrp':
[Progress: 130 / 438]
Module 'Magento_Search':
[Progress: 131 / 438]
Module 'Magento_CatalogUrlRewrite':
Running schema recurring...
[Progress: 132 / 438]
Module 'Magento_Widget':
[Progress: 133 / 438]
Module 'Magento_Quote':
[Progress: 134 / 438]
Module 'Magento_CheckoutAgreements':
[Progress: 135 / 438]
Module 'Magento_SalesSequence':
[Progress: 136 / 438]
Module 'Magento_CmsUrlRewrite':
[Progress: 137 / 438]
Module 'Magenerds_BasePrice':
[Progress: 138 / 438]
Module 'Magento_ConfigurableImportExport':
[Progress: 139 / 438]
Module 'Magento_Payment':
[Progress: 140 / 438]
Module 'Magento_Contact':
[Progress: 141 / 438]
Module 'Magento_Cookie':
[Progress: 142 / 438]
Module 'Magento_Cron':
[Progress: 143 / 438]
Module 'Magento_CurrencySymbol':
[Progress: 144 / 438]
Module 'Magento_User':
[Progress: 145 / 438]
Module 'Magento_CustomerImportExport':
[Progress: 146 / 438]
Module 'Magento_Deploy':
[Progress: 147 / 438]
Module 'Magento_Developer':
[Progress: 148 / 438]
Module 'Magento_Dhl':
[Progress: 149 / 438]
Module 'Magento_Authorization':
[Progress: 150 / 438]
Module 'Magento_Downloadable':
[Progress: 151 / 438]
Module 'Magento_ImportExport':
[Progress: 152 / 438]
Module 'Magento_CatalogInventory':
Running schema recurring...
[Progress: 153 / 438]
Module 'Magento_Email':
[Progress: 154 / 438]
Module 'Magento_EncryptionKey':
[Progress: 155 / 438]
Module 'Magento_Fedex':
[Progress: 156 / 438]
Module 'Magento_Sales':
[Progress: 157 / 438]
Module 'Magento_Checkout':
[Progress: 158 / 438]
Module 'Magento_GoogleAnalytics':
[Progress: 159 / 438]
Module 'Magento_Ui':
[Progress: 160 / 438]
Module 'Magento_GroupedImportExport':
[Progress: 161 / 438]
Module 'Magento_GroupedProduct':
[Progress: 162 / 438]
Module 'Magento_DownloadableImportExport':
[Progress: 163 / 438]
Module 'Magento_Bundle':
Running schema recurring...
[Progress: 164 / 438]
Module 'Magento_Security':
[Progress: 165 / 438]
Module 'Magento_LayeredNavigation':
[Progress: 166 / 438]
Module 'Magento_Marketplace':
[Progress: 167 / 438]
Module 'Magento_MediaStorage':
[Progress: 168 / 438]
Module 'Magento_CatalogRule':
[Progress: 169 / 438]
Module 'Magento_Multishipping':
[Progress: 170 / 438]
Module 'Magento_ConfigurableProduct':
Running schema recurring...
[Progress: 171 / 438]
Module 'Magento_Newsletter':
[Progress: 172 / 438]
Module 'Magento_OfflinePayments':
[Progress: 173 / 438]
Module 'Magento_SalesRule':
[Progress: 174 / 438]
Module 'Magento_PageCache':
[Progress: 175 / 438]
Module 'Magento_Vault':
[Progress: 176 / 438]
Module 'Magento_Paypal':
[Progress: 177 / 438]
Module 'Magento_Persistent':
[Progress: 178 / 438]
Module 'Magento_ProductAlert':
Running schema recurring...
[Progress: 179 / 438]
Module 'Magento_ProductVideo':
[Progress: 180 / 438]
Module 'Magento_Captcha':
[Progress: 181 / 438]
Module 'Magento_Reports':
Running schema recurring...
[Progress: 182 / 438]
Module 'Magento_RequireJs':
[Progress: 183 / 438]
Module 'Magento_Review':
[Progress: 184 / 438]
Module 'Magento_Rss':
[Progress: 185 / 438]
Module 'Magento_CatalogRuleConfigurable':
[Progress: 186 / 438]
Module 'Magento_NewRelicReporting':
[Progress: 187 / 438]
Module 'Magento_SalesInventory':
[Progress: 188 / 438]
Module 'Magento_OfflineShipping':
[Progress: 189 / 438]
Module 'Magento_Authorizenet':
[Progress: 190 / 438]
Module 'Magento_SampleData':
[Progress: 191 / 438]
Module 'Magento_CatalogSearch':
[Progress: 192 / 438]
Module 'Magento_Integration':
Running schema recurring...
[Progress: 193 / 438]
Module 'Magento_SendFriend':
[Progress: 194 / 438]
Module 'Magento_Shipping':
[Progress: 195 / 438]
Module 'Magento_Sitemap':
[Progress: 196 / 438]
Module 'Magento_GoogleAdwords':
[Progress: 197 / 438]
Module 'Magento_Swagger':
[Progress: 198 / 438]
Module 'Magento_Swatches':
[Progress: 199 / 438]
Module 'Magento_SwatchesLayeredNavigation':
[Progress: 200 / 438]
Module 'Magento_Tax':
[Progress: 201 / 438]
Module 'Magento_TaxImportExport':
[Progress: 202 / 438]
Module 'Magento_GiftMessage':
[Progress: 203 / 438]
Module 'Magento_Translation':
[Progress: 204 / 438]
Module 'Magento_GoogleOptimizer':
[Progress: 205 / 438]
Module 'Magento_Ups':
[Progress: 206 / 438]
Module 'Magento_UrlRewrite':
[Progress: 207 / 438]
Module 'Magenerds_GermanLaw':
[Progress: 208 / 438]
Module 'Magento_Usps':
[Progress: 209 / 438]
Module 'Magento_Variable':
[Progress: 210 / 438]
Module 'Magento_Braintree':
[Progress: 211 / 438]
Module 'Magento_Version':
[Progress: 212 / 438]
Module 'Magento_Webapi':
[Progress: 213 / 438]
Module 'Magento_WebapiSecurity':
[Progress: 214 / 438]
Module 'Magento_Weee':
Running schema recurring...
[Progress: 215 / 438]
Module 'Magento_CatalogWidget':
[Progress: 216 / 438]
Module 'Magento_Wishlist':
Running schema recurring...
[Progress: 217 / 438]
DDL cache cleared successfully
[Progress: 218 / 438]
Installing user configuration...
[Progress: 219 / 438]
Enabling caches:
Current status:
Array
(
    [config] => 1
    [layout] => 1
    [block_html] => 1
    [collections] => 1
    [reflection] => 1
    [db_ddl] => 1
    [eav] => 1
    [customer_notification] => 1
    [full_page] => 1
    [config_integration] => 1
    [config_integration_api] => 1
    [translate] => 1
    [config_webservice] => 1
)

[Progress: 220 / 438]
Installing data...
Data install/update:
Module 'Magento_Store':
[Progress: 221 / 438]
Module 'Magenerds_Dashboard':
[Progress: 222 / 438]
Module 'Magento_Directory':
Installing data...
[Progress: 223 / 438]
Module 'Magento_Theme':
Installing data... Upgrading data...
[Progress: 224 / 438]
Module 'Magento_AdvancedPricingImportExport':
[Progress: 225 / 438]
Module 'Magento_Backend':
[Progress: 226 / 438]
Module 'Magento_Eav':
Installing data...
[Progress: 227 / 438]
Module 'Magento_Customer':
Installing data... Upgrading data...
[Progress: 228 / 438]
Module 'Magento_Backup':
[Progress: 229 / 438]
Module 'Magento_AdminNotification':
[Progress: 230 / 438]
Module 'Magento_Indexer':
Installing data...
[Progress: 231 / 438]
Module 'Magento_BundleImportExport':
[Progress: 232 / 438]
Module 'Magento_CacheInvalidate':
[Progress: 233 / 438]
Module 'Magento_Cms':
Installing data... Upgrading data...
[Progress: 234 / 438]
Module 'Magento_Config':
Installing data...
[Progress: 235 / 438]
Module 'Magento_CatalogImportExport':
[Progress: 236 / 438]
Module 'Magento_Catalog':
Installing data... Upgrading data...
[Progress: 237 / 438]
Module 'Magento_Rule':
[Progress: 238 / 438]
Module 'Magento_Msrp':
Installing data... Upgrading data...
[Progress: 239 / 438]
Module 'Magento_Search':
[Progress: 240 / 438]
Module 'Magento_CatalogUrlRewrite':
Installing data...
[Progress: 241 / 438]
Module 'Magento_Widget':
Installing data...
[Progress: 242 / 438]
Module 'Magento_Quote':
Installing data...
[Progress: 243 / 438]
Module 'Magento_CheckoutAgreements':
[Progress: 244 / 438]
Module 'Magento_SalesSequence':
Installing data...
[Progress: 245 / 438]
Module 'Magento_CmsUrlRewrite':
[Progress: 246 / 438]
Module 'Magenerds_BasePrice':
Installing data...

                                                                        
  [Magento\Framework\Exception\NoSuchEntityException]                   
  Attribute with attributeCode "baseprice_product_unit" does not exist.

**Comment by sydekumf** [comment]
Hi,
which Magento version do you use?

**Comment by JSchlarb** [comment]
I can confirm it by using 2ee 2.15. It depends on one of this params. 
```
    --language=de_DE \
    --currency=EUR \
    --use-rewrites=0 \
    --cleanup-database
```

**Comment by m-schreiber** [comment]
Here is the composer.json:

{
    "name": "magento/project-community-edition",
    "description": "eCommerce Platform for Growth (Community Edition)",
    "type": "project",
    "version": "2.1.5",
    "license": [
        "OSL-3.0",
        "AFL-3.0"
    ],
    "require": {
        "magento/product-community-edition": "2.1.5",
        "magenerds/language-de_de": "1.0.8",
        "magenerds/germanlaw": "dev-master"
        "composer/composer": "1.1.2 as 1.0.0-beta1"
    },
    "require-dev": {
        "phpunit/phpunit": "4.1.0",
        "squizlabs/php_codesniffer": "1.5.3",
        "phpmd/phpmd": "@stable",
        "pdepend/pdepend": "2.2.2",
        "fabpot/php-cs-fixer": "~1.2",
        "lusitanian/oauth": "~0.3 <=0.7.0",
        "sebastian/phpcpd": "2.0.0"
    },
    "config": {
        "use-include-path": true,
        "secure-http": false
    },
    "autoload": {
        "psr-4": {
            "Magento\\Framework\\": "lib/internal/Magento/Framework/",
            "Magento\\Setup\\": "setup/src/Magento/Setup/",
            "Magento\\": "app/code/Magento/"
        },
        "psr-0": {
            "": "app/code/"
        },
        "files": [
            "app/etc/NonComposerComponentRegistration.php"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Magento\\Sniffs\\": "dev/tests/static/framework/Magento/Sniffs/",
            "Magento\\Tools\\": "dev/tools/Magento/Tools/",
            "Magento\\Tools\\Sanity\\": "dev/build/publication/sanity/Magento/Tools/Sanity/",
            "Magento\\TestFramework\\Inspection\\": "dev/tests/static/framework/Magento/TestFramework/Inspection/",
            "Magento\\TestFramework\\Utility\\": "dev/tests/static/framework/Magento/TestFramework/Utility/"
        }
    },
    "minimum-stability": "alpha",
    "prefer-stable": true,
    "repositories": [
        {
            "type": "composer",
            "url": "https://repo.magento.com/"
        }
    ],
    "extra": {
        "magento-force": "override"
    }
}

**Comment by sydekumf** [comment]
Thanks for reporting, the fix is included in this release: https://github.com/Magenerds/BasePrice/releases/tag/1.0.9
