### ISSUE TITLE
Group Products are not supported

### ISSUE THREAD

**Issue by Prime-Host** [Magenerds/BasePrice#9]
One of your employees Florian wrote to me, that i should create a issue on the Github site of this project. 

Simple and configurable Products are working with thix extension. But as far as i know group Products are not supported. I am not familiar enough with magento to wrote the code by myself to solve this Problem.
Is it planed to support group products with this extension in the future?

If you need more information please let me know.

regards
Kevin Nordloh

**Comment by sydekumf** [comment]
Grouped products are now supported in this release: https://github.com/Magenerds/BasePrice/releases/tag/1.1.0
